//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCMStrategyEntities : DbContext
    {
        public BCMStrategyEntities()
            : base("name=BCMStrategyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activitytype> activitytype { get; set; }
        public virtual DbSet<apiclient> apiclient { get; set; }
        public virtual DbSet<auditlog> auditlog { get; set; }
        public virtual DbSet<audittables> audittables { get; set; }
        public virtual DbSet<audittype> audittype { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<committee> committee { get; set; }
        public virtual DbSet<contentloaderlog> contentloaderlog { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<dailyfrequency> dailyfrequency { get; set; }
        public virtual DbSet<defaultlexiconterms> defaultlexiconterms { get; set; }
        public virtual DbSet<designation> designation { get; set; }
        public virtual DbSet<documentstorage> documentstorage { get; set; }
        public virtual DbSet<dynamictablesfieldsfornounplusverb> dynamictablesfieldsfornounplusverb { get; set; }
        public virtual DbSet<dynamictablesfornounplusverb> dynamictablesfornounplusverb { get; set; }
        public virtual DbSet<emailgenerationchartimage> emailgenerationchartimage { get; set; }
        public virtual DbSet<emailgenerationstatus> emailgenerationstatus { get; set; }
        public virtual DbSet<emailtemplate> emailtemplate { get; set; }
        public virtual DbSet<euentities> euentities { get; set; }
        public virtual DbSet<eurpeanunionentities> eurpeanunionentities { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<frequency> frequency { get; set; }
        public virtual DbSet<globalconfiguration> globalconfiguration { get; set; }
        public virtual DbSet<individuallegislators> individuallegislators { get; set; }
        public virtual DbSet<individuallegislatorscommittee> individuallegislatorscommittee { get; set; }
        public virtual DbSet<individuallegislatorsdesignation> individuallegislatorsdesignation { get; set; }
        public virtual DbSet<instance> instance { get; set; }
        public virtual DbSet<institution> institution { get; set; }
        public virtual DbSet<institutiontypes> institutiontypes { get; set; }
        public virtual DbSet<internationalorganizations> internationalorganizations { get; set; }
        public virtual DbSet<lexiconissuelinker> lexiconissuelinker { get; set; }
        public virtual DbSet<lexiconissues> lexiconissues { get; set; }
        public virtual DbSet<lexiconprivilege> lexiconprivilege { get; set; }
        public virtual DbSet<lexicontype> lexicontype { get; set; }
        public virtual DbSet<loadererrorlog> loadererrorlog { get; set; }
        public virtual DbSet<loaderlinkdocuments> loaderlinkdocuments { get; set; }
        public virtual DbSet<loaderlinklog> loaderlinklog { get; set; }
        public virtual DbSet<loaderlinkqueue> loaderlinkqueue { get; set; }
        public virtual DbSet<metadatanounplusverb> metadatanounplusverb { get; set; }
        public virtual DbSet<metadataphrases> metadataphrases { get; set; }
        public virtual DbSet<metadatatypes> metadatatypes { get; set; }
        public virtual DbSet<metadatavalue> metadatavalue { get; set; }
        public virtual DbSet<modules> modules { get; set; }
        public virtual DbSet<parentmenu> parentmenu { get; set; }
        public virtual DbSet<policymakers> policymakers { get; set; }
        public virtual DbSet<processeventlog> processeventlog { get; set; }
        public virtual DbSet<processevents> processevents { get; set; }
        public virtual DbSet<processinstances> processinstances { get; set; }
        public virtual DbSet<processtypes> processtypes { get; set; }
        public virtual DbSet<refreshtoken> refreshtoken { get; set; }
        public virtual DbSet<relatedactivitytypes> relatedactivitytypes { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<rolemodulerights> rolemodulerights { get; set; }
        public virtual DbSet<scanninglinkdetails> scanninglinkdetails { get; set; }
        public virtual DbSet<scanninglinkqueue> scanninglinkqueue { get; set; }
        public virtual DbSet<schedular> schedular { get; set; }
        public virtual DbSet<schedularfrequency> schedularfrequency { get; set; }
        public virtual DbSet<scrapedcontents> scrapedcontents { get; set; }
        public virtual DbSet<scrapeddocumentdetails> scrapeddocumentdetails { get; set; }
        public virtual DbSet<scrapedlexiconmapping> scrapedlexiconmapping { get; set; }
        public virtual DbSet<scraperengineconfiguration> scraperengineconfiguration { get; set; }
        public virtual DbSet<scraperenginesetup> scraperenginesetup { get; set; }
        public virtual DbSet<scrappedproprietorytags> scrappedproprietorytags { get; set; }
        public virtual DbSet<scrappedproprietorytagsmapping> scrappedproprietorytagsmapping { get; set; }
        public virtual DbSet<scrappedstandardtag_policymakers> scrappedstandardtag_policymakers { get; set; }
        public virtual DbSet<scrappedstandardtags> scrappedstandardtags { get; set; }
        public virtual DbSet<scrappedstandardtags_sectors> scrappedstandardtags_sectors { get; set; }
        public virtual DbSet<scrapperstandardtags_entitytypes> scrapperstandardtags_entitytypes { get; set; }
        public virtual DbSet<sector> sector { get; set; }
        public virtual DbSet<statehead> statehead { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<submenu> submenu { get; set; }
        public virtual DbSet<topiccodes> topiccodes { get; set; }
        public virtual DbSet<urlexclusionlist> urlexclusionlist { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<useraccessrights> useraccessrights { get; set; }
        public virtual DbSet<useractivationlink> useractivationlink { get; set; }
        public virtual DbSet<weblinkactivitytype> weblinkactivitytype { get; set; }
        public virtual DbSet<weblinkpagecontentregex> weblinkpagecontentregex { get; set; }
        public virtual DbSet<weblinkpolicymaker> weblinkpolicymaker { get; set; }
        public virtual DbSet<weblinkproprietarytags> weblinkproprietarytags { get; set; }
        public virtual DbSet<weblinkrss> weblinkrss { get; set; }
        public virtual DbSet<weblinks> weblinks { get; set; }
        public virtual DbSet<weblinksector> weblinksector { get; set; }
        public virtual DbSet<websitetypes> websitetypes { get; set; }
        public virtual DbSet<weburlcategorymapping> weburlcategorymapping { get; set; }
        public virtual DbSet<legislatorsview> legislatorsview { get; set; }
        public virtual DbSet<multilateralviewforscrapperactivity> multilateralviewforscrapperactivity { get; set; }
    }
}
