//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class dynamictablesfornounplusverb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dynamictablesfornounplusverb()
        {
            this.dynamictablesfieldsfornounplusverb = new HashSet<dynamictablesfieldsfornounplusverb>();
        }
    
        public int Id { get; set; }
        public string DynamicType { get; set; }
        public string TableName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dynamictablesfieldsfornounplusverb> dynamictablesfieldsfornounplusverb { get; set; }
    }
}
