//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailgenerationchartimage
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> GenerationDate { get; set; }
        public byte[] ChartImage { get; set; }
        public Nullable<System.DateTime> UpdationDate { get; set; }
    }
}
