//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class frequency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public frequency()
        {
            this.scraperenginesetup = new HashSet<scraperenginesetup>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Occurs { get; set; }
        public Nullable<int> RecursDaily { get; set; }
        public Nullable<int> RecursMonday { get; set; }
        public Nullable<int> RecursTuesday { get; set; }
        public Nullable<int> RecursWednesday { get; set; }
        public Nullable<int> RecursThursday { get; set; }
        public Nullable<int> RecursFriday { get; set; }
        public Nullable<int> RecursSaturday { get; set; }
        public Nullable<int> RecursSunday { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scraperenginesetup> scraperenginesetup { get; set; }
    }
}
