//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class individuallegislatorscommittee
    {
        public int Id { get; set; }
        public int IndividualLegislatorsId { get; set; }
        public int CommitteeId { get; set; }
    
        public virtual committee committee { get; set; }
        public virtual individuallegislators individuallegislators { get; set; }
    }
}
