//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class internationalorganizations
    {
        public int Id { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string LeaderFirstName { get; set; }
        public string LeaderLastName { get; set; }
        public string EntityName { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsMultiLateral { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual designation designation { get; set; }
    }
}
