//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class lexiconissues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lexiconissues()
        {
            this.defaultlexiconterms = new HashSet<defaultlexiconterms>();
            this.lexiconissuelinker = new HashSet<lexiconissuelinker>();
            this.lexiconprivilege = new HashSet<lexiconprivilege>();
            this.scrapedlexiconmapping = new HashSet<scrapedlexiconmapping>();
        }
    
        public int Id { get; set; }
        public int LexiconTypeId { get; set; }
        public string LexiconIssue { get; set; }
        public string CombinationValue { get; set; }
        public bool IsNested { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<defaultlexiconterms> defaultlexiconterms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lexiconissuelinker> lexiconissuelinker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lexiconprivilege> lexiconprivilege { get; set; }
        public virtual lexicontype lexicontype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scrapedlexiconmapping> scrapedlexiconmapping { get; set; }
    }
}
