//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class lexiconissuelinker
    {
        public int Id { get; set; }
        public int LexiconIssueId { get; set; }
        public string Linkers { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual lexiconissues lexiconissues { get; set; }
    }
}
