//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaderlinklog
    {
        public int Id { get; set; }
        public string InstanceName { get; set; }
        public int WebSiteId { get; set; }
        public string SiteURL { get; set; }
        public int ProcessId { get; set; }
        public int ProcessInstanceId { get; set; }
        public string Guid { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> LinkLevel { get; set; }
        public Nullable<bool> IsSuccessful { get; set; }
        public Nullable<decimal> WebLinkBytes { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> LinkCreatedDate { get; set; }
        public Nullable<int> NewProcessId { get; set; }
        public Nullable<int> LexiconCount { get; set; }
    
        public virtual processevents processevents { get; set; }
        public virtual processevents processevents1 { get; set; }
        public virtual processinstances processinstances { get; set; }
        public virtual status status { get; set; }
        public virtual weblinks weblinks { get; set; }
    }
}
