//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class metadatavalue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public metadatavalue()
        {
            this.weblinkactivitytype = new HashSet<weblinkactivitytype>();
        }
    
        public int Id { get; set; }
        public int MetaDataTypeId { get; set; }
        public Nullable<int> ActivityTypeId { get; set; }
        public decimal ActivityValue { get; set; }
    
        public virtual activitytype activitytype { get; set; }
        public virtual metadatatypes metadatatypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weblinkactivitytype> weblinkactivitytype { get; set; }
    }
}
