//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class metadatatypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public metadatatypes()
        {
            this.metadatanounplusverb = new HashSet<metadatanounplusverb>();
            this.metadataphrases = new HashSet<metadataphrases>();
            this.scrappedproprietorytagsmapping = new HashSet<scrappedproprietorytagsmapping>();
            this.metadatavalue = new HashSet<metadatavalue>();
            this.weblinkproprietarytags = new HashSet<weblinkproprietarytags>();
        }
    
        public int Id { get; set; }
        public int WebSiteTypeId { get; set; }
        public string MetaData { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<bool> IsActivityTypeExist { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<metadatanounplusverb> metadatanounplusverb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<metadataphrases> metadataphrases { get; set; }
        public virtual websitetypes websitetypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scrappedproprietorytagsmapping> scrappedproprietorytagsmapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<metadatavalue> metadatavalue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weblinkproprietarytags> weblinkproprietarytags { get; set; }
    }
}
