//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class metadatanounplusverb
    {
        public int Id { get; set; }
        public int MetaDataTypeId { get; set; }
        public string Noun { get; set; }
        public string Verb { get; set; }
        public bool IsHardCoded { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ActivityTypeId { get; set; }
    
        public virtual activitytype activitytype { get; set; }
        public virtual metadatatypes metadatatypes { get; set; }
    }
}
