//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class refreshtoken
    {
        public string Id { get; set; }
        public string ClientId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> IssuedDateTime { get; set; }
        public Nullable<System.DateTime> ExpiresDateTime { get; set; }
        public string ProtectedKey { get; set; }
    
        public virtual apiclient apiclient { get; set; }
        public virtual user user { get; set; }
    }
}
