//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolemodulerights
    {
        public int Id { get; set; }
        public int ModuleId { get; set; }
        public int RoleId { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> Brexit { get; set; }
        public Nullable<bool> RegulatoryCapital { get; set; }
        public Nullable<bool> Trade { get; set; }
        public Nullable<bool> FinTech { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual modules modules { get; set; }
        public virtual role role { get; set; }
        public virtual user user { get; set; }
    }
}
