//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class scanninglinkdetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scanninglinkdetails()
        {
            this.documentstorage = new HashSet<documentstorage>();
            this.scrappedstandardtags = new HashSet<scrappedstandardtags>();
            this.scrapedcontents = new HashSet<scrapedcontents>();
            this.scrappedproprietorytags = new HashSet<scrappedproprietorytags>();
        }
    
        public int Id { get; set; }
        public int ScannerLinkId { get; set; }
        public string WebSiteURL { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public int ProcessInstanceId { get; set; }
        public string Guid { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int PageType { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentstorage> documentstorage { get; set; }
        public virtual processevents processevents { get; set; }
        public virtual processinstances processinstances { get; set; }
        public virtual scanninglinkqueue scanninglinkqueue { get; set; }
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scrappedstandardtags> scrappedstandardtags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scrapedcontents> scrapedcontents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scrappedproprietorytags> scrappedproprietorytags { get; set; }
    }
}
