//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class scanninglinkqueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scanninglinkqueue()
        {
            this.scanninglinkdetails = new HashSet<scanninglinkdetails>();
        }
    
        public int Id { get; set; }
        public int WebSiteId { get; set; }
        public Nullable<sbyte> ReadTaken { get; set; }
        public string Guid { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual processevents processevents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scanninglinkdetails> scanninglinkdetails { get; set; }
        public virtual weblinks weblinks { get; set; }
    }
}
