//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class scrapperstandardtags_entitytypes
    {
        public int Id { get; set; }
        public int ScrappedStandardTagId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> EntityTypeId { get; set; }
    
        public virtual country country { get; set; }
        public virtual institution institution { get; set; }
        public virtual institutiontypes institutiontypes { get; set; }
        public virtual scrappedstandardtags scrappedstandardtags { get; set; }
    }
}
