//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class scraperenginesetup
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int WebSiteId { get; set; }
        public string EmailStatus { get; set; }
        public int FrequencyId { get; set; }
        public int DailyFrequencyId { get; set; }
        public Nullable<System.DateTime> DurationStartDate { get; set; }
        public Nullable<System.DateTime> DurationEndDate { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual client client { get; set; }
        public virtual dailyfrequency dailyfrequency { get; set; }
        public virtual frequency frequency { get; set; }
        public virtual status status1 { get; set; }
        public virtual weblinks weblinks { get; set; }
    }
}
