//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class scraperengineconfiguration
    {
        public int Id { get; set; }
        public Nullable<int> ThresholdValue { get; set; }
        public Nullable<decimal> TimeTaken { get; set; }
        public Nullable<int> NoOfInstances { get; set; }
    }
}
