//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class scrappedstandardtags_sectors
    {
        public int Id { get; set; }
        public Nullable<int> ScrappedStandardTagsId { get; set; }
        public Nullable<int> SectorId { get; set; }
    
        public virtual scrappedstandardtags scrappedstandardtags { get; set; }
        public virtual sector sector { get; set; }
    }
}
