//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class scrappedproprietorytagsmapping
    {
        public int Id { get; set; }
        public int ScrappedProprietoryTagId { get; set; }
        public Nullable<int> MetaDataTypeId { get; set; }
        public string SearchType { get; set; }
        public Nullable<int> SearchTypeId { get; set; }
        public Nullable<decimal> SearchValue { get; set; }
        public Nullable<int> SearchCounts { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> ActivityTypeId { get; set; }
    
        public virtual activitytype activitytype { get; set; }
        public virtual metadatatypes metadatatypes { get; set; }
        public virtual scrappedproprietorytags scrappedproprietorytags { get; set; }
    }
}
