//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class scrappedproprietorytags
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public scrappedproprietorytags()
        {
            this.scrappedproprietorytagsmapping = new HashSet<scrappedproprietorytagsmapping>();
        }
    
        public int Id { get; set; }
        public int ScanningLinkDetailId { get; set; }
        public byte[] Content { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual scanninglinkdetails scanninglinkdetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scrappedproprietorytagsmapping> scrappedproprietorytagsmapping { get; set; }
    }
}
