//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class scrapedlexiconmapping
    {
        public int Id { get; set; }
        public int LexiconId { get; set; }
        public string LexiconsTerms { get; set; }
        public int ScrapedContentid { get; set; }
        public Nullable<int> IssuesCount { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual lexiconissues lexiconissues { get; set; }
        public virtual scrapedcontents scrapedcontents { get; set; }
    }
}
