//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class useractivationlink
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string UserActivationCode { get; set; }
        public string ForceReset { get; set; }
        public System.DateTime ExpiredDateTime { get; set; }
    
        public virtual user user { get; set; }
    }
}
