//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class weblinkactivitytype
    {
        public int Id { get; set; }
        public int WebLinkId { get; set; }
        public int MetaDataTypeId { get; set; }
    
        public virtual metadatavalue metadatavalue { get; set; }
        public virtual weblinks weblinks { get; set; }
    }
}
