//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCMStrategy.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class weburlcategorymapping
    {
        public int Id { get; set; }
        public int WebSiteId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual country country { get; set; }
        public virtual weblinks weblinks { get; set; }
    }
}
